### ISSUE TITLE
Rename the Wiki pages to not contain a '?' in title

### ISSUE THREAD

**Issue by zocker1996** [Musta1337/TeknoMW3#2]
There are two pages in the wiki,
`How to enable the server list?`
and
`How to verify my game files with Steam?`,
which contain a questionmark (`?`) in the title.
If you try to clone the wiki (e.g. to have a archive copy on your local machine) using 
`git clone https://github.com/Musta1337/TeknoMW3.wiki.git`
this two files can not be extracted, since `?` is an illegal character for a file name (at least on Windows).
Could you please remove the `?` from the wiki pages :) ?

**Comment by SoyRA** [comment]
I don't think I'll do that, since I should change all the links that are sent to that page. /:
If you haven't found something to help you, you could download it manually:
\- [How-to-enable-the-server-list%3F.md](https://raw.githubusercontent.com/wiki/Musta1337/TeknoMW3/How-to-enable-the-server-list%3F.md)
\- [How-to-verify-my-game-files-with-Steam%3F.md](https://raw.githubusercontent.com/wiki/Musta1337/TeknoMW3/How-to-verify-my-game-files-with-Steam%3F.md)

**Comment by SoyRA** [comment]
Jum...I think it's done, now everything should be fine.
